name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify index.html exists
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found!"
            exit 1
          fi

      - name: Verify assets folder exists
        run: |
          if [ ! -d assets ]; then
            echo "assets folder not found!"
            exit 1
          fi

      - name: Upload Website Artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-artifact
          path: |
            index.html
            assets/